### ISSUE TITLE
open source projects list

### ISSUE THREAD

**Issue by WeileiZeng** [VincentFokker/Fruitpunch-AI-Covid-19#1]
Hi I am the maintainer of this list https://weileizeng.github.io/Open-Source-COVID-19/ and I think your project is interesting.

Are you just collecting informations, or are doing some data analysis by your group?

**Comment by VincentFokker** [comment]
Hi Radish,

Thanks for the interest in our project. This Git its main purpose is to
facilitate our team in data analysis. We are doing some analysis in
preparation for our global challenge together with Omdena (a worldwide
collaborative of volunteers) starting the 26th of march. We are aming to
work towards a first insights publication (on medium) before the 26th of
march.

Kind regards, Met vriendelijke groet,

*Vincent Fokker*
*Fruitpunch AI *
---
in: www.linkedin.com/in/vincent-fokker


Op ma 16 mrt. 2020 om 23:10 schreef Radish Meeting <notifications@github.com

**Comment by WeileiZeng** [comment]
sounds good. I am adding your project with an "analysis" tag

**Comment by WeileiZeng** [comment]
Added.
